M48
; DRILL file {KiCad (6.0.9)} date Sun Jan 15 17:57:30 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-15T17:57:30-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X67.425Y-68.77
X67.425Y-115.72
X91.935Y-68.77
X91.935Y-115.72
T0
M30
